name: Upload Release Asset

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install
        run: 
          npm ci
      - name: Build
        run: 
          npm run package
      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          files: |
            edgefirst.detect-*.foxe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}